### ISSUE TITLE
Discussion: Integration different target platforms

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu-sw#3]
@DanMueGri reached out to me that we would like to support using an `ESP32(C3)` with the MLonMCU flow. While it would be theoretically possible to integrate the toolchain/linker files/... inside this repository but at some point the complexity increases too much.

Maybe we should consider using `arduino-cli` or `platformio` to build/deploy target software for such targets. The question is then how the interface between MLonMCU and those tools may look like and if there are further caveats we need to consider.

**Comment by fabianpedd** [comment]
The alternative to using `arduino-cli` or `platformio` would be to directly use the [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html) if I am understanding correctly? 

The ESP-IDF already provides a handy [Python tool](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html#step-8-build-the-project) that makes life quite easy. I would say it **could** also be an option to simply interface with that using mlonmcu.

**Comment by PhilippvK** [comment]
@fabianpedd I also consider that. However the main problem is, that such approach would not scale well as every new non-Espressif target would require another platform. With something like Arduino/PlatformIO we would theoretically be able to support a large number of targets at once. However the question is if we actually want/need this.

**Comment by PhilippvK** [comment]
Another thing we need to keep in mind is that while we would be able to build and deploy the target software fairly especially we also need to be able to build static libraries for specific features such as MuriscvNN with the respective toolchain. Currently I have no idea if this would be possible with the aforementioned tools.

**Comment by fabianpedd** [comment]
>  With something like Arduino/PlatformIO we would theoretically be able to support a large number of targets at once. However the question is if we actually want/need this.

I just want to point out, that while PlatformIO does provide a lot of dependency/toolchain management, it does not provide a common programming API for different platforms like Arduino does. 

As an example, if you want to blink an LED using PlatformIO on any ESP32 chip (they all use the ESP-IDF, which in turn builds on top of FreeRTOS) your code would have to look something like this:

```
void app_main()
{
    /* Configure the IOMUX register for pad BLINK_GPIO (some pads are
       muxed to GPIO on reset already, but some default to other
       functions and need to be switched to GPIO. Consult the
       Technical Reference for a list of pads and their default
       functions.)
    */
    gpio_pad_select_gpio(BLINK_GPIO);
    /* Set the GPIO as a push/pull output */
    gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
    while(1) {
        /* Blink off (output low) */
	printf("Turning off the LED\n");
        gpio_set_level(BLINK_GPIO, 0);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        /* Blink on (output high) */
	printf("Turning on the LED\n");
        gpio_set_level(BLINK_GPIO, 1);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
}
```
[Source](https://github.com/platformio/platform-espressif32/blob/develop/examples/espidf-blink/src/blink.c).


If you wanted to blink an LED using PlatformIO on an STM32F0 (here using libopencm3) you would have to:
```
int main(void)
{
	int i;
	rcc_periph_clock_enable(RCCLEDPORT);
        gpio_mode_setup(LEDPORT, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, LEDPIN);
	/* Blink the LED on the board. */
	while (1) {
		/* Using API function gpio_toggle(): */
		gpio_toggle(LEDPORT, LEDPIN);	/* LED on/off */
		for (i = 0; i < 1000000; i++) {	/* Wait a bit. */
			__asm__("nop");
		}
	}

	return 0;
}
```
[Source](https://github.com/platformio/platform-ststm32/blob/master/examples/libopencm3-blink/src/main.c)

So even when using PlatformIO, your application code won't be portable across chips / ISAs / manufacturers. Sometimes not even across APIs / hardware abstraction layers. For the STM32, for example, there are a number of different APIs one can use when working with PlatformIO: CMSIS, LibOpenCM3, MBed, STM32cube, Zephyr, [etc](https://github.com/platformio/platform-ststm32/tree/master/examples). In PlatformIO they are called ["Frameworks"](https://docs.platformio.org/en/stable/frameworks/index.html).


When using Arduino however, your application blink code will look (almost) exactly the same for all platforms:
```
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}

```
[Source](https://www.arduino.cc/en/Tutorial/BuiltInExamples/Blink)

This is because vendors provide abstraction layers for their platforms that all have the same, common Arduino API. Here is [Espressif's](https://github.com/espressif/arduino-esp32), and here the code for the [STM32 boards](https://github.com/stm32duino/Arduino_Core_STM32).

So in this sense, using Arduino is "more convenient". However, you lock yourself into using this common interface and might not benefit from vendor-specific API features. 

PlatformIO does not provide portability in this sense. It only provides an extra layer of convenience when it comes to different toolchains and IDEs. It does not provide a common API, as Arduino does.

As far as I can see, mlonmcu is trying to be like PlatformIO for ML. Providing a commonplace (toolchain, dependency management, deployment, testing, simulation, etc.) for all things ML on microcontrollers. So I am sceptical if using PlatformIO is actually bringing any value to mlonmcu, since mlonmcu is already doing a lot of the things PlatformIO does. I instead suspect that it might be just another layer "on top", that has to be taken care of. But that is just my take and there might be benefits I am missing.

**Comment by PhilippvK** [comment]
Closing as MLonMCU now supports a "Platform API"
